## 準備のため

In [131]:
import numpy as np

In [132]:
A = np.arange(1, 10) ** 5
B = np.arange(1, 10) ** 5

X, Y = np.meshgrid(A, B)

print(X)
print(Y)

Z = Y - X
print(Z)

[[    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]
 [    1    32   243  1024  3125  7776 16807 32768 59049]]
[[    1     1     1     1     1     1     1     1     1]
 [   32    32    32    32    32    32    32    32    32]
 [  243   243   243   243   243   243   243   243   243]
 [ 1024  1024  1024  1024  1024  1024  1024  1024  1024]
 [ 3125  3125  3125  3125  3125  3125  3125  3125  3125]
 [ 7776  7776  7776  7776  7776  7776  7776  7776  7776]
 [16807 16807 16807 16807 16807 16807 16807 16807 16807]
 [32768 32768 32768 32768 32768 32768 32768 32768 32768]
 [59049 59049 59049 59049 5904

In [133]:
def factoring_pair(n):
    result = []
    for i in range(2, int(n ** 0.5 + 1)):
        if n % i != 0: continue
        counter = 0
        while n % i == 0:
            n //= i
            counter += 1
        result.append((i, counter))
    if n != 1:
        result.append((n, 1))
    return result

In [134]:
nums = list(set(Z[Z > 0]))
nums.sort()

print(nums)

for n in nums:
    print(factoring_pair(n))

[31, 211, 242, 781, 992, 1023, 2101, 2882, 3093, 3124, 4651, 6752, 7533, 7744, 7775, 9031, 13682, 15783, 15961, 16564, 16775, 16806, 24992, 26281, 29643, 31744, 32525, 32736, 32767, 42242, 51273, 55924, 58025, 58806, 59017, 59048]
[(31, 1)]
[(211, 1)]
[(2, 1), (11, 2)]
[(11, 1), (71, 1)]
[(2, 5), (31, 1)]
[(3, 1), (11, 1), (31, 1)]
[(11, 1), (191, 1)]
[(2, 1), (11, 1), (131, 1)]
[(3, 1), (1031, 1)]
[(2, 2), (11, 1), (71, 1)]
[(4651, 1)]
[(2, 5), (211, 1)]
[(3, 5), (31, 1)]
[(2, 6), (11, 2)]
[(5, 2), (311, 1)]
[(11, 1), (821, 1)]
[(2, 1), (6841, 1)]
[(3, 1), (5261, 1)]
[(11, 1), (1451, 1)]
[(2, 2), (41, 1), (101, 1)]
[(5, 2), (11, 1), (61, 1)]
[(2, 1), (3, 1), (2801, 1)]
[(2, 5), (11, 1), (71, 1)]
[(41, 1), (641, 1)]
[(3, 1), (41, 1), (241, 1)]
[(2, 10), (31, 1)]
[(5, 2), (1301, 1)]
[(2, 5), (3, 1), (11, 1), (31, 1)]
[(7, 1), (31, 1), (151, 1)]
[(2, 1), (21121, 1)]
[(3, 5), (211, 1)]
[(2, 2), (11, 1), (31, 1), (41, 1)]
[(5, 2), (11, 1), (211, 1)]
[(2, 1), (3, 5), (11, 2)]
[(7, 1), (8431

In [135]:
from functools import partial

In [136]:
n = 59048
factors = factoring_pair(n)
factors

[(2, 3), (11, 2), (61, 1)]

$A - B$の幅を固定しながら動かして、二分探索で求める値があるかどうかを探す

In [137]:
def binary_search(condition, min, max):
    while max - min > 1:
        mid = int((max + min) // 2)
        if condition(mid):
            min = mid
        else:
            max = mid
    return min

In [138]:
def A5_B5(seg, b):
    a = b + seg
    return a ** 5 - b ** 5  

def is_OK(n, seg, b):
    return A5_B5(seg, b) <= n

for seg in range(1, 13):
    res = binary_search(partial(is_OK, n, seg), 1, 100)
    print((seg, res), A5_B5(seg, res), A5_B5(seg, res) == n)

(1, 9) 40951 False
(2, 7) 42242 False
(3, 6) 51273 False
(4, 5) 55924 False
(5, 4) 58025 False
(6, 3) 58806 False
(7, 2) 59017 False
(8, 1) 59048 True
(9, 1) 99999 False
(10, 1) 161050 False
(11, 1) 248831 False
(12, 1) 371292 False


In [139]:
A5_B5(5, 1)

7775

# 解答

In [140]:
90**5 - (-2)**5

5904900032

In [1]:
from functools import partial

def A5_B5(seg, b):
    a = b + seg
    return a ** 5 - b ** 5  

def is_OK(n, seg, b):
    return A5_B5(seg, b) <= n

def binary_search(condition, min, max):
    while max - min > 1:
        mid = int((max + min) // 2)
        if condition(mid):
            min = mid
        else:
            max = mid
    return min

if __name__ == "__main__":
    X = int(input())

    for seg in range(1, int(X ** 0.5)+2):
        res = binary_search(partial(is_OK, X, seg), -seg-1, X)
        if A5_B5(seg, res) == X:
            print(res+seg, res)
            break

2 -1


In [4]:
from functools import partial

def A5_B5(seg, b):
    a = b + seg
    return a ** 5 - b ** 5  

def is_OK(n, seg, b):
    return A5_B5(seg, b) <= n

def binary_search(condition, min, max):
    while max - min > 1:
        mid = int((max + min) // 2)
        if condition(mid):
            min = mid
        else:
            max = mid
    return min

if __name__ == "__main__":
    X = 962449399
    seg = 108

    res = binary_search(partial(is_OK, X, seg), -seg-1, X)
    print(res+seg, res)


57 -51
